services:
  portfolio.web:
    image: portfolio.web
    ports:
      - "8090:8080"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Portfolio/Dockerfile
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
    driver: local
